### ISSUE TITLE
undefined reference to `__imp_vsscript_init'

### ISSUE THREAD

**Issue by sofakng** [qyot27/mpv#4]
I"m trying to re-create your script by manually running the steps and I was able to cross-compile Python 3.8.2 and VapourSynth (R49-RC1) but when mpv tries to link everything I get the following errors:

`video/filter/vf_vapoursynth.c.20.o: In function 'drv_vss_init':
/usr/local/src/mingw32/mpv/build/../../../mpv/video/filter/vf_vapoursynth.c:814: undefined reference to '__imp_vsscript_init'`

...and a bunch of other undefined references to __imp_vsscript_*.

Any idea what might be causing this?  I can see it's linking with "-lvapoursynth' and '-lvapoursynth-script'

**Comment by qyot27** [comment]
mingw32?  If this is a 32-bit build, that will fail.  There's a note about that in the build instructions.

**Comment by sofakng** [comment]
no, I'm using 64-bit.  (MXE, x86_64-w64-mingw32.static)

**Comment by qyot27** [comment]
Has -DVS_CORE_EXPORTS been passed to FFmpeg and mpv?

**Comment by sofakng** [comment]
Hmmm, I didn't enable vapoursynth with ffmpeg.  If I try to enable it then I get the same undefined reference.

However, if I add --extra-cflags="-DVS_CORE_EXPORTS" to ffmpeg configure, it returns a different set of errors about libpthread:  multiple definition of `pthread_once'

Are you by chance on discord to chat for a few minutes?

**Comment by sofakng** [comment]
I've been able to figure it out and was user error.  (i.e. my fault!)
